# 本地运行的配置文件
[Server]
AppMode = "debug" # debug 开发环境， release 生产环境
BackPort = ":8081" # 后台服务端口
FrontPort = ":8082" # 前台服务端口

[JWT]
Secret = "abc123321"
Expire = 24 # 过期时间 （小时）
Issuer = "gin-vue-blog"

[Mysql]
Host = "10.122.0.11"
Port = "13306"
Config = "" # 其他配置， 例如时区
Dbname = "gvb" # 数据库名称
Username = "root"
Password = "123456" # 数据库密码
# 日志级别 silent, error, warn, info, 默认 info
LogMode = "error" # silent 相当于关闭日志

[Redis]
DB = 7
Addr = '10.122.0.11:6379'
Password = ''

[Session]
Name = "mysession"
Salt = "salt"
MaxAge = 600 # 秒

# 配置发送验证码账号信息
[Email]
Host = "smtp.163.com" # 服务器地址，后面自行选择！！！
Port = 465 # 同样是后面自行获取，多个可能的选择
Form = "" # 自行填写（发送人邮箱）
ISSSL = true # 是否开启SSL
Secret = " " # 密钥， 不是邮箱登录密码，是开启 smtp 服务后获取的一串验证码
Nickname = "" # 发件人邮箱
# 可惜现在我不能下好

[Zap]
Level = "error" #日志级别：debug, info, warn, error, dpanic, panic, fatal, 默认 info
Format = "console" #日志输出格式： console, json
Perfix = "[GIN-VUE-BLOG_HUFENG" #日志前缀
Directory = "log"
ShowLine = true # 是否显示哪行调用
LogInConsole = true # 是否输出到控制台

[Upload]
OssType = "local" # 控制存储：local、qiniu
StorePath = "public/uploaded" # 本地文件上传路径
Path = "public/uploaded" # 本地文件访问路径
# Markdown 目前只支持本地上传 （目前使用前端导出，该配置无效）（那为什么不挂起来）
MdPath = "public/markdown" # Markdown 访问路径
MdStorePath = "public/markdown" # Markdown 上传路径